- BaekJoon/스터디/1006 습격자 초라기.py
- BaekJoon/스터디/1007 벡터 매칭.py
- BaekJoon/스터디/1010 다리놓기.py
문제 이해가 어려웠던 문제.
방법은 이렇게 하면 되겠다 라고 생각이 드는데 코드 구현을 어떻게 해야 할지 고민 했던 문제.
방법.
1. 모든 x, y 좌표들의 합을 구한다.
2. 각 점의 절반에 해당 하는 부분의 x, y 좌표들의 합을 구한다.
3. 1.에서 구했던 합과 2.에서 구했던 합을 빼면 2.에서 구했던 반대 점의 절반의 x, y 좌표들의 합이 구해진다.
4. 2.에서 구한 합과 3.에서 구한 합의 벡터의 최소값을 구하면 된다.
수도 코드
```python
P = [모든 점의 좌표.]
for x, y in P:
total_x += x
total_y += y
result = 10**10
combi = combination(B, len(P) // 2 )
for combi_P in combi[:len(combi) // 2]:
for x, y in combi_P:
half_x1 += x
half_y1 += y
half_x2 = total_x - half_x1
half_y2 = total_y - half_y1
result = min(result, ((half_x1 - half_x2)**2 + (half_y1 - half_y2)**2)**0.5)
print(result)
```
> 1007: 벡터 매칭

- BaekJoon/스터디/10171 고양이.py
<p>\ 뒤에 문자가 있으면 특수 문자.</p>
\n | 줄바꿈
-- | --
\t | 탭 ( tab )
\\ | 백슬래시 ( \ )
\’ | 작은따옴표 ( ‘ )
\” | 큰따옴표 ( “ )
<pre><code class="language-python"># ex)
print(&quot;\\\\&quot;)
&gt;&gt; \\
</code></pre>
> 10171: 고양이

- BaekJoon/스터디/2525 오븐 시계.py
[[몫과 나머지 구분 - divmod](https://www.notion.so/divmod-1149438fb762494bb9121ab5b2af3e97?pvs=21)](https://www.notion.so/divmod-1149438fb762494bb9121ab5b2af3e97?pvs=21)
> 2525: 오븐 시계

- BaekJoon/스터디/5597 과제 안 내신 분.py
pop으로 할 경우 리스트에서 요소를 뽑아낸 후 리스트의 갱신이 일어나지 않기에 오류가 발생한다.
따라서 pop 부분을 remove로 바꿔서 진행할 경우 해결 된다.
> 5597 과제 안 내신분

- BaekJoon/Algorithm_study/2941 크로아티아 알파벳.py
특수문자 처리
[[re](https://www.notion.so/re-155405b92cc24813b1d06cd0af7ef931?pvs=21)](https://www.notion.so/re-155405b92cc24813b1d06cd0af7ef931?pvs=21)
> 2941: 크로아티아 알파벳;

- BaekJoon/Algorithm_study/1316 그룹 단어 체커.py
- BaekJoon/Algorithm_study/25206 너의 평점은.py
> 25206: 너의 평점은

- BaekJoon/Algorithm_study/10798 세로읽기.py
- BaekJoon/Algorithm_study/_test.ipynb
ljust 사용하여 문자열 채움.
[[문자열 자리수 채우기](https://www.notion.so/acc7b314603b4718af0f7bd8a330429b?pvs=21)](https://www.notion.so/acc7b314603b4718af0f7bd8a330429b?pvs=21)
> 10798: 세로 읽기

- BaekJoon/Algorithm_study/1978 Bronze 소수 찾기.py
- BaekJoon/Algorithm_study/2869 Bronze 달팽이는 올라가고 싶다.py
소수 구하는 함수.
[[소수 판별](https://www.notion.so/7ef40f8788104ac98a41cd5296c8929e?pvs=21)](https://www.notion.so/7ef40f8788104ac98a41cd5296c8929e?pvs=21)
> 1978: 소수 찾기

- BaekJoon/Algorithm_study/11653 Bronze 소인수분해.py
- BaekJoon/Algorithm_study/2581 Bronze 소수.py
divmod 사용
[몫과 나머지 구분 - divmod](https://www.notion.so/divmod-1149438fb762494bb9121ab5b2af3e97?pvs=21)
> 11653: 소인수분해

- BaekJoon/Algorithm_study/3009 Bronze 네 번째 점.py
x, y 위치의 동일한 값은 제외하고 다른 값들만 모으면 사각형의 마지막 점.
> 3009: 네 번째 점

- BaekJoon/Algorithm_study/5073 Bronze 삼각형과 세 변.py
삼각형의 조건
- 가장 긴 변 > 다른 두 변의 합
정삼각형 : Equilateral
이등변 삼각형 : Isosceles
삼각형 : Scalene
> 5073: 삼각형과 세 변

- BaekJoon/Algorithm_study/24262 알고리즘 수업 - 알고리즘의 수행 시간 1.py
함수의 시간 복잡도 출력.
[[빅오 표기법, 시간복잡도](https://www.notion.so/a5f2a1e8b5b748f6b82a50d97ecc2d28?pvs=21)](https://www.notion.so/a5f2a1e8b5b748f6b82a50d97ecc2d28?pvs=21)
> 24262: 알고리즘 수업 - 알고리즘의 수행 시간 1

- BaekJoon/Algorithm_study/24265 Bronze 알고리즘 수업 - 알고리즘의 수행 시간 4.py
함수 실행해서 횟수 카운트 하면 시간 초과 뜸.
1 부터 n - 1 까지의 합을 구하면 됨.
1 ~ 10까지의 합 공식 = 10 * (10 + 1) / 2
> 24265: 알고리즘 수업 - 알고리즘의 수행시간 4

- BaekJoon/Algorithm_study/24267 Bronze 알고리즘 수업 - 알고리즘의 수행 시간 6.py
시간 복잡도, 빅오 표기법
[[빅오 표기법, 시간복잡도](https://www.notion.so/a5f2a1e8b5b748f6b82a50d97ecc2d28?pvs=21)](https://www.notion.so/a5f2a1e8b5b748f6b82a50d97ecc2d28?pvs=21)
> 24267: 알고리즘수업

- BaekJoon/Algorithm_study/1018 Silver 체스판 다시 칠하기.py
8 * 8 의 체스판을 만든다는 말이 이해가 처음에 잘 안갔다.
8 * 8에 맞는 보드를 하나씩 체크해가면서 체스판이 맞는지 확인 하면 됨.
> 1018:  체스판 다시 칠하기

- BaekJoon/Algorithm_study/2839 Silver 설탕 배달.py
5로 나눴을때의 최대 몫에서부터 남은 부분을 3으로 나눴을 때 딱 떨어지는지 확인.
안떨어지면 남은 부분 5씩 증가해서 3으로 나눠 떨어지는지 확인
값이 없을 때 그리고 나머지부분이 조금이라도 남아있으면 -1, 그 외는 두 몫의 합.
> 2839: 설탕 배달

- BaekJoon/Algorithm_study/11650 Silver 좌표 정렬하기.py
sort key lambda 사용.
[[sort key도 가능](https://www.notion.so/sort-key-7376a131f3a049f0bc029ba755f47bfc?pvs=21)](https://www.notion.so/sort-key-7376a131f3a049f0bc029ba755f47bfc?pvs=21)
> 11650: 좌표 정렬하기

- BaekJoon/Algorithm_study/11651 Silver 좌표 정렬하기 2.py
Sort lambda 이용해서 풀면 됨.
[[Python sorted](https://www.notion.so/Python-sorted-3e3e7bf211914292b7689300b265c556?pvs=21)](https://www.notion.so/Python-sorted-3e3e7bf211914292b7689300b265c556?pvs=21)
> 11651: 좌표 정렬하기 2;

- BaekJoon/Algorithm_study/10814 Silver 나이순 정렬.py
sort  key lambda 사용하면 쉽게 풀 수 있음.
나이부분 정렬할 떄 문자열로 놔두고 정렬하면 안됨. int형태로 놔두고 바꿔야함.
> 10814: 나이순 정렬

- BaekJoon/Algorithm_study/18870 Silver 좌표 압축.py
[[Python dict key, value 추가 딕셔너리 원소 추가](https://www.notion.so/Python-dict-key-value-e1405c8ff17a46a19d2078eccb33cdda?pvs=21)](https://www.notion.so/Python-dict-key-value-e1405c8ff17a46a19d2078eccb33cdda?pvs=21)
mapping 해서 안하면 시간 제한 걸림.
넣어야 하는 값들만 맵핑해서 idx 넣어놓고
중복 제거 한 후 정렬해서 하나씩 idx 뽑아서 그 위치에 값을 오름차순으로 넣으면 됨.
> 18870: 좌표 압축

- BaekJoon/Algorithm_study/7785 Silver 회사에 있는 사람.py
사전순 역순 정렬
dictionary 형태로 넣어야 뽑아올 때 빠름.
[[길이가 같으면 사전 순으로](https://www.notion.so/dc55a92363a4440eb6f2fe78cbaaab7c?pvs=21)](https://www.notion.so/dc55a92363a4440eb6f2fe78cbaaab7c?pvs=21)
> 7785: 회사에 있는 사람;

- BaekJoon/Algorithm_study/10816 Silver 숫자 카드 2.py
dictionary에 저장해놓고 찾으면 빠르게 찾을 수 있음.
get 함수 사용. 값이 없으면 0 값이 있으면 그 값을 가져옴.
[[Python dict key, value 추가 딕셔너리 원소 추가](https://www.notion.so/Python-dict-key-value-e1405c8ff17a46a19d2078eccb33cdda?pvs=21)](https://www.notion.so/Python-dict-key-value-e1405c8ff17a46a19d2078eccb33cdda?pvs=21)
> feat: :white_check_mark: 10816: 숫자 카드

- BaekJoon/Algorithm_study/1764 Silver 듣보잡.py
dictionary 형태로 get 으로 불러오면 빠르게 처리 할 수 있음.
마지막에 sort로 사전순 정렬까지 진행.
[[Python dict key, value 추가 딕셔너리 원소 추가](https://www.notion.so/Python-dict-key-value-e1405c8ff17a46a19d2078eccb33cdda?pvs=21)](https://www.notion.so/Python-dict-key-value-e1405c8ff17a46a19d2078eccb33cdda?pvs=21)
[[Python sorted](https://www.notion.so/Python-sorted-3e3e7bf211914292b7689300b265c556?pvs=21)](https://www.notion.so/Python-sorted-3e3e7bf211914292b7689300b265c556?pvs=21)
> feat: 1764: 듣보잡

- BaekJoon/Algorithm_study/11478 Silver 서로 다른 부분 문자열 개수.py
> 11478: 서로 다른 부분 문자열 개수;

- BaekJoon/Algorithm_study/4134 Silver 다음 소수.py
아.. 소수 판별 함수로 풀면 됨.
그런데 예외 처리 제대로 해야함. 최소, 최대 소수값 잘 찾기…
[[소수 판별](https://www.notion.so/7ef40f8788104ac98a41cd5296c8929e?pvs=21)](https://www.notion.so/7ef40f8788104ac98a41cd5296c8929e?pvs=21)
> 4134: 다음 소수

- BaekJoon/Algorithm_study/13909 Silver 창문 닫기.py
- BaekJoon/Algorithm_study/17103 Silver 골드바흐 파티션.py
제곱수일 때만 창문의 개수가 1개씩 늘어난다.
내림을 이용.
[[Python 반올림, 내림, 올림](https://www.notion.so/Python-3064dbd4fa394d0cbab2c896391ca802?pvs=21)](https://www.notion.so/Python-3064dbd4fa394d0cbab2c896391ca802?pvs=21)
> 13909: 창문 닫기

- BaekJoon/Algorithm_study/17103 Silver 골드바흐 파티션.py
소수 리스트를 만들어서 체크해야 시간 초과 안뜸.
[[소수 판별](https://www.notion.so/7ef40f8788104ac98a41cd5296c8929e?pvs=21)](https://www.notion.so/7ef40f8788104ac98a41cd5296c8929e?pvs=21)
> 17103: 골드흐 파티션

- BaekJoon/Algorithm_study/9012 Silver 괄호.py
올바른 괄호인지 확인 하는 함수를 사용하면 쉽게 풀림.
[[올바른 괄호인지 판별](https://www.notion.so/fb2a9c35ed174c2d91c45ea825b7a0cc?pvs=21)](https://www.notion.so/fb2a9c35ed174c2d91c45ea825b7a0cc?pvs=21)
> 9012: 올바른 괄호

- BaekJoon/Algorithm_study/4949 Silver 균형잡힌 세상.py
strip은 rstrip 해야함. 안그럼 틀림.
괄호 확인하는 함수 사용하면 됨.
[[올바른 괄호인지 판별](https://www.notion.so/fb2a9c35ed174c2d91c45ea825b7a0cc?pvs=21)](https://www.notion.so/fb2a9c35ed174c2d91c45ea825b7a0cc?pvs=21)
> 4949: 균형잡힌 세상

- BaekJoon/Algorithm_study/18258 Silver 큐 2.py
큐에서 가장 앞에 있는거 뺀다는데.. 가장 안쪽에 있는거 빼야됨.
> 18258: 큐 2

- BaekJoon/Algorithm_study/11866 Silver 요세푸스 문제 0.py
마지막 숫자를 뽑아 냈을 때는 0번 위치 부터 다시 돌아야 함.
“, ‘ 프린트 할 때 주의
> 11866: 요세푸스 문제 0

- BaekJoon/Algorithm_study/28279 Silver 덱 2.py
deque 사용하면 금방 풀림.
[[파이썬 Deque - pop, push 리스트보다 빠름](https://www.notion.so/Deque-pop-push-64372aac99ea4b4a83b5feb6f61f70ec?pvs=21)](https://www.notion.so/Deque-pop-push-64372aac99ea4b4a83b5feb6f61f70ec?pvs=21)
> 28279: 덱 2

- BaekJoon/Algorithm_study/24511 Silver queuestack.py
문제 이해하면 쉬움.
A는 큐인지 스텍인지 알려주고
B가 리스트 형태로 원소들이 들어가있음.
M 개의 C 가 주어지는데
각 C를 입력 받았을 때
B의 길이만큼 큐이면 해당 idx에 값을 넣고 넣어져 있던 값을 리턴함.
스텍이면 넣고 그 값을 그대로 빼기 때문에 그냥 패스하면 됨.
- 위 방법대로 하면 시간 초과 뜸.
일단 que인 값들만 뽑아오고
c를 받아 앞에 넣고 que 마지막 값 뽑아서 result에 넣어야함.
> 24511: queuestack

- BaekJoon/Algorithm_study/15439 Bronze 베라의 패션.py
> 15439: 베라의 패션

- BaekJoon/Algorithm_study/26069 붙임성 좋은 총총이.py
ChongChong을 만났는데 춤추는 사람이 없으면 둘 다 춤추는 사람에 넣고, 그 뒤로 춤추는 사람과 만난 사람이 있으면 춤추는 사람에 추가.
set에 추가해서 같은 사람 제거.
> 26069: 붙임성 좋은 총총이

- BaekJoon/Algorithm_study/11729 Gold 하노이 탑 이동 순서.py
[[하노이 탑](https://www.notion.so/64e92cb022f34d96b9c100297af29124?pvs=21)](https://www.notion.so/64e92cb022f34d96b9c100297af29124?pvs=21) 
움직이는 부분에 global 로 변수 두고 하나씩 카운트 하면 됨.
1일 때도 반환 해줘야함.
> 11729: 하노이탑 이동 순서

- BaekJoon/Algorithm_study/27433 Bronze 팩토리얼 2.py
팩토리얼 쓰면 됨.
[[Python 경우의 수 팩토리얼](https://www.notion.so/Python-6b6faa99bab14c9cbc1f850e07182506?pvs=21)](https://www.notion.so/Python-6b6faa99bab14c9cbc1f850e07182506?pvs=21)
> 27433: 팩토리얼 2

- BaekJoon/Algorithm_study/10870 Bronze 피보나치 수 5.py
피보나치 수 사용 하면 됨
[[피보나치](https://www.notion.so/29bb27dec1bc44d4b732abce21651471?pvs=21)](https://www.notion.so/29bb27dec1bc44d4b732abce21651471?pvs=21)
> 10870: 피보나치 수 5

- BaekJoon/Algorithm_study/25501 Bronze 재귀의 귀재.py
> 25501: 재귀의 귀재

- BaekJoon/Algorithm_study/24060 Silver 알고리즘 수업 - 병합 정렬 1.py
[[병합 정렬 Merge Sort](https://www.notion.so/Merge-Sort-634c6f12fb72410bb2f765c9a897b0b4?pvs=21)](https://www.notion.so/Merge-Sort-634c6f12fb72410bb2f765c9a897b0b4?pvs=21) 
병합 정렬을 이용하여 풀이.
class 형태로 구현하여 문제 풀이.
> 24060: 알고리즘 수업 - 병합 정렬 1

- BaekJoon/Algorithm_study/4779 Silver 칸토어 집합.py
입력 제한 없을 때 사용 하는 방법
[[입력 제한 없을 때](https://www.notion.so/b44861a08f00457f9dbb8f82c8789517?pvs=21)](https://www.notion.so/b44861a08f00457f9dbb8f82c8789517?pvs=21) 
-이 N 증가 할 때 마다 s + ‘ ‘ * len(s) + s 로 추가하면 됨.
> 4779: 칸토어 집합

- BaekJoon/Algorithm_study/15650 Silver N과 M (2).py
itertools combinations 사용
[[Python 순열, 조합, product - itertools](https://www.notion.so/Python-product-itertools-1311c62b2ea94dd6b395471f37033fc8?pvs=21)](https://www.notion.so/Python-product-itertools-1311c62b2ea94dd6b395471f37033fc8?pvs=21)
> 15650: N과 M (2)

- BaekJoon/Algorithm_study/15652 Silver N과 M (4).py
값을 하나씩 증가하면서 이전 값들보다 낮으면 같을 때까지 증가.
> 15652: N과 M (4)

- BaekJoon/Algorithm_study/9663 Gold N-Queen.py
x 축 체크, 대각선 체크를 y축 만큼 진행해서 문제 없으면 result + 1씩 증가.
x + y 가 같거나 x - y가 같으면 같은 대각선에 위치 함을 이용
> 9663: N-Queen

- BaekJoon/Algorithm_study/10986 Gold 나머지 합.py
누적으로 더하고 M 값으로 나눠지는 값이 나오면 그 값만큼 추가로 더해서 진행.
> 10986: 나머지 합

- BaekJoon/Algorithm_study/11047 Silver 동전 0.py
큰 동전부터 나머지, 몫 구해서 계산하면 됨.
[[몫과 나머지 구분 - divmod](https://www.notion.so/divmod-1149438fb762494bb9121ab5b2af3e97?pvs=21)](https://www.notion.so/divmod-1149438fb762494bb9121ab5b2af3e97?pvs=21) 
[[Greedy](https://www.notion.so/Greedy-2511577dc2444422bbbf3a07ab7f3151?pvs=21)](https://www.notion.so/Greedy-2511577dc2444422bbbf3a07ab7f3151?pvs=21)
> 11047: 동전 0

- BaekJoon/Algorithm_study/1032 Bronze 명령 프롬프트.py
> 1032: 명령 프롬프트

- BaekJoon/Algorithm_study/14888 Silver 연산자 끼워넣기.py
[[Python Graph(Floyd-Warshall), BFS, DFS](https://www.notion.so/Python-Graph-Floyd-Warshall-BFS-DFS-685c87ff79bf481c8ea7631450e7285a?pvs=21)](https://www.notion.so/Python-Graph-Floyd-Warshall-BFS-DFS-685c87ff79bf481c8ea7631450e7285a?pvs=21)
> 14888: 연산자 끼워넣기
